name: frontend

on:
  push:
    paths:
    - ".github/workflows/frontend.yml"
    - "html/*"
  pull_request:
    paths:
    - ".github/workflows/frontend.yml"
    - "html/*"

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: html/yarn.lock
      - name: Run yarn install, check and build
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install
          yarn run check
          yarn run build
        working-directory: html
